config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :description %>
<%= f.input :number_of_guests %>
<%= f.input :price_per_night %>
<%= f.submit "Create Flat", class: "btn btn-primary" %>
<%= link_to "Cancel", flats_path %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6">
      <div class="flat-form">
        <h1>Edit Flat</h1>
        <%= render 'form', flat: @flat %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>All our Flats (<%= @flats.count %>)</h1>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-xs-4">
      <div class="card flats-card">
        <!-- <div class="flat-card-image" style=""></div> -->
        <div class="card flats-content">
          <h4><%= flat.name %></h4>
          <p><%= flat.address %></p>
          <div class="flats-details">
            <i class="fas fa-users"></i><span><%= flat.number_of_guests %></span>
            <i class="fas fa-euro-sign"></i><span><%= flat.price_per_night %></span>
          </div>
        </div>
        <div class="card flats-actions">
          <%= link_to "More info", flat_path(flat) %>
          <%= link_to "Edit", edit_flat_path(flat) %>
          <%= link_to "Remove", flat_path(flat), method: :delete %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <%= render 'form', flat: @flat %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-8">
      <div class="card flat-card">
        <h2><%= @flat.name %></h2>
        <h4><%= @flat.address %></h4>
      </div>

      <div class="card flat-card">
        <h2>A bit more about this flat...</h2>
        <p><%= @flat.description %></p>
      </div>

      <div class="card flat-card">
        <h2>Details</h2>
        <div class="flat-details">
          <i class="fas fa-users"></i><span><%= @flat.number_of_guests %></span>
          <i class="fas fa-euro-sign"></i><span><%= @flat.price_per_night %></span>
        </div>
      </div>
    </div>

    <div class="col-xs-4">
      <div class="card flat-card">
        <h4>Book this place!</h4>
        <form action="#" class="form-group">
          <input type="date" class="form-control input-form">
          <input type="date" class="form-control input-form">
          <input type="submit" value="Book" class="form-control btn btn-success">
        </form>
      </div>

      <div class="card flat-card flat-share">
        <div class="share">
          <h4>Share</h4>
        </div>
        <div class="icons">
          <i class="fab fa-facebook-square"></i>
          <i class="fab fa-twitter-square"></i>
          <i class="fab fa-pinterest-square"></i>
          <i class="fas fa-envelope-square"></i>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-airbnb">
      <%= link_to "Simple Airbnb", flats_path, class: "brand-airbnb" %>
      <div class="flex">
        <%= link_to "Add Flat", new_flat_path, class: "btn-airbnb" %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>